networks:
  devcontainer-network:
    name: hivebalance-network

volumes:
  postgres-data:
  pgadmin-data:
  m2-cache:


services:
  app:
    container_name: hivebalance-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1010
        USER_GID: 1010
    env_file:
      - ../.env.development
    volumes:
      - ../..:/workspaces:cached
      # Maven cache
      - m2-cache:/home/${USERNAME}/.m2
    ports:
      - "8085:8080"
    networks:
      - devcontainer-network
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Use "forwardPorts" in **devcontainer.tmp.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    container_name: postgresdb
    image: postgres:17.2
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - devcontainer-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - devcontainer-network