referenceUrl=hibernate:spring:ch.reidyt.hivebalance?dialect=org.hibernate.dialect.PostgreSQLDialect\
&hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy\
&hibernate.implicit_naming_strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl